/* Written by Noah Brayer 9/14/2013 */
#include <stdio.h>					// Includes Header File: "stdio" 
double getSide(void);					// Prototype Function: "getSide"
double calculateArea(double);				// Prototype Function: "calculateArea"
double calculatePerimeter(double);			// Prototype Function: "calculatePerimeter"
void printArea(double);					// Prototype Function: "printArea"
void printPerimeter(double);				// Prototype Function: "printPerimeter"
void main(void)						// Defines: Function: "main"
{	double side;					// Declares Variable: "side"
	side=getSide();					// Invokes Function: "getSide"
	printArea(calculateArea(side));			// Invokes Function: "printArea", "calculateArea"
	printPerimeter(calculatePerimeter(side));	// Invokes Function: "printPerimeter", "calculatePerimeter"
} 							// Ends: Function: "main"
double getSide(void)					// Defines: Function: "getSide"
{	double side;					// Declares Variable: "side"
	printf("Input side length:>"); 			// Prompts Variable: 'side'
	scanf("%lf",&side);				// Inputs Variable: "side"
	return(side);					// Return for function: "getSide"
}							// Ends: Function: "getSide"
double calculateArea(double side)			// Defines: Function: "calculateArea"
{	return(side*side);				// Calculation and return for function: "calculateArea"
}							// Ends: Function: "calculateArea"
double calculatePerimeter(double side)			// Defines: Function: "calculatePerimeter"
{	return(4*side);					// Calculation and return for function: "calculatePerimeter"
}							// Ends: Function: "calculatePerimeter"
void printArea(double area)				// Defines: Function: "printArea"
{	printf("Your area is %.3lf, \n",area);		// Output: 'area'
}							// Ends: Function: "printArea"
void printPerimeter(double perimeter)			// Defines: Function: "printPerimeter"
{printf("and your perimeter is %.3lf.",perimeter);	// Output: 'perimeter'
}							// Ends: Function: "printPerimeter"